config/routes.rb
Rails.application.routes.draw do
  get '/parse_url' => 'api/v1/parsers#parse_url'
end

app/models/datum.rb
class Datum < ActiveRecord::Base
end

app/models/parser.rb
class Parser < ActiveRecord::Base
end

app/controllers/api/v1/parsers_controller.rb
class Api::V1::ParsersController < ApplicationController
	skip_before_action :verify_authenticity_token
  require 'open-uri'
  require 'nokogiri'

  def parse_url
  	data = params[:link]
    if data
      html_doc = Nokogiri::HTML(open(data))
      h1_array = []
      h2_array = []
      h3_array = []
      link_array = []

      h1_nodes = html_doc.search("//h1")
      h1_nodes.each do |node|
        h1_array.push node.to_s.gsub("<h1>", "").gsub("</h1>", "")
      end

      h2_nodes = html_doc.search("//h2")
      h2_nodes.each do |node|
        h2_array.push node.to_s.gsub("<h2>", "").gsub("</h2>", "")
      end

      h3_nodes = html_doc.search("//h3")
      h3_nodes.each do |node|
        h3_array.push node.to_s.gsub("<h3>", "").gsub("</h3>", "")
      end

      link_nodes = html_doc.css('a')
      link_nodes.each do |node|
        link_array.push node["href"].to_s
      end
      parser = Parser.new(h1: h1_array, h2: h2_array, h3: h3_array, link: link_array)
      if parser.save!
        render :json => {success: true, data: parser.to_json}
      else
        render :json => {success: false, message: "Something Went Wrong."}
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parsers_helper.rb
module ParsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lims</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parsers/_form.html.erb
<%= form_for(@parser) do |f| %>
  <% if @parser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parser.errors.count, "error") %> prohibited this parser from being saved:</h2>

      <ul>
      <% @parser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :h1 %><br>
    <%= f.text_field :h1 %>
  </div>
  <div class="field">
    <%= f.label :h2 %><br>
    <%= f.text_field :h2 %>
  </div>
  <div class="field">
    <%= f.label :h3 %><br>
    <%= f.text_field :h3 %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parsers/edit.html.erb
<h1>Editing Parser</h1>

<%= render 'form' %>

<%= link_to 'Show', @parser %> |
<%= link_to 'Back', parsers_path %>

app/views/parsers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parsers</h1>

<table>
  <thead>
    <tr>
      <th>H1</th>
      <th>H2</th>
      <th>H3</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parsers.each do |parser| %>
      <tr>
        <td><%= parser.h1 %></td>
        <td><%= parser.h2 %></td>
        <td><%= parser.h3 %></td>
        <td><%= parser.link %></td>
        <td><%= link_to 'Show', parser %></td>
        <td><%= link_to 'Edit', edit_parser_path(parser) %></td>
        <td><%= link_to 'Destroy', parser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parser', new_parser_path %>

app/views/parsers/new.html.erb
<h1>New Parser</h1>

<%= render 'form' %>

<%= link_to 'Back', parsers_path %>

app/views/parsers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>H1:</strong>
  <%= @parser.h1 %>
</p>

<p>
  <strong>H2:</strong>
  <%= @parser.h2 %>
</p>

<p>
  <strong>H3:</strong>
  <%= @parser.h3 %>
</p>

<p>
  <strong>Link:</strong>
  <%= @parser.link %>
</p>

<%= link_to 'Edit', edit_parser_path(@parser) %> |
<%= link_to 'Back', parsers_path %>